(define (inferieure? duree1 duree2)
  (let ((total1 (+ (* (jours-dans-duree duree1) 86400)
                   (* (heures-dans-duree duree1) 3600)
                   (* (minutes-dans-duree duree1) 60)
                   (secondes-dans-duree duree1)))
        (total2 (+ (* (jours-dans-duree duree2) 86400)
                   (* (heures-dans-duree duree2) 3600)
                   (* (minutes-dans-duree duree2) 60)
                   (secondes-dans-duree duree2))))
    (< total1 total2)))

(define (inferieure? duree1 duree2)
  (let ((total1 (+ (* (car duree1) 86400)
                   (* (cadr duree1) 3600)
                   (* (caddr duree1) 60)
                   (cadddr duree1)))
        (total2 (+ (* (car duree2) 86400)
                   (* (cadr duree2) 3600)
                   (* (caddr duree2) 60)
                   (cadddr duree2))))
    (< total1 total2)))
