(define (drawAr slenAr)
  (draw slenAr)
  (turn (- 0 60))
  (draw slenAr)
  (turn 120)
  (draw slenAr)
  (turn (- 0 60))
  (draw slenAr)
  )

;(define (tracecote nbAr angl lenAr)
;  (cond ((> nbAr 1)
;        (draw lenAr)
;        (turn (- 180 angl))
;        (tracecote (- nbAr 1) angl lenAr))
;        ((= nbAr 1)
;         (draw lenAr))))